using Microsoft.EntityFrameworkCore;
using TaskBoard.WebApi;

var builder = WebApplication.CreateBuilder(args);

var connectionString = builder.Configuration.GetConnectionString("TaskBoardDatabase")
    ?? "Host=localhost;Port=5433;Database=taskboard_sample;Username=postgres;Password=postgres";

builder.Services.AddDbContext<SampleDbContext>(options => options
    .UseNpgsql(connectionString)
    .UseNpgsqlNotifications());

var app = builder.Build();

// Applies any pending migrations on startup, which is what actually creates the notification
// trigger/trigger function generated by PgNotify.Migrations — see Migrations/ for the
// checked-in migration produced by `dotnet ef migrations add InitialCreate`. This app never
// listens for notifications itself; see ../TaskBoard.Watcher for the separate process that does.
using (var scope = app.Services.CreateScope())
{
    await scope.ServiceProvider.GetRequiredService<SampleDbContext>().Database.EnsureCreatedAsync();
}

app.UseDefaultFiles();
app.UseStaticFiles();

app.MapTaskEndpoints();

app.Run();

public partial class Program;
