using CacheInvalidation.WebApi;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

var connectionString = builder.Configuration.GetConnectionString("SampleDatabase")
    ?? "Host=localhost;Database=cache_invalidation_sample;Username=postgres;Password=postgres";

builder.Services.AddDbContext<SampleDbContext>(options => options
    .UseNpgsql(connectionString)
    .UseNpgsqlNotifications());

builder.Services.AddMemoryCache();

builder.Services.AddPostgresNotifications(options =>
{
    options.AddHandlersFromAssembly(typeof(Program).Assembly);
    options.UseLogging();

    // No channel names and no connection string above: both are derived from SampleDbContext's
    // model when the host starts, because it chained UseNpgsqlNotifications(). The channel a
    // handler listens on is therefore stated exactly once, by the entity configuration that also
    // generates the trigger.
    options.AddNotificationMappingFromDbContexts();
});

var app = builder.Build();

// Applies any pending migrations on startup, which is what actually creates the notification
// trigger/trigger function generated by PgNotify.Migrations — see Migrations/ for the
// checked-in migration produced by `dotnet ef migrations add InitialCreate`.
using (var scope = app.Services.CreateScope())
{
    await scope.ServiceProvider.GetRequiredService<SampleDbContext>().Database.MigrateAsync();
}

app.MapProductEndpoints();
app.MapHealthChecks("/health");

app.Run();

public partial class Program;
