using Microsoft.EntityFrameworkCore;
using Orders.WebApi;

var builder = WebApplication.CreateBuilder(args);

var connectionString = builder.Configuration.GetConnectionString("OrdersDatabase")
    ?? "Host=localhost;Port=5434;Database=orders_sample;Username=postgres;Password=postgres";

builder.Services.AddDbContext<SampleDbContext>(options => options
    .UseNpgsql(connectionString)
    .UseNpgsqlNotifications());

var app = builder.Build();

// Applies any pending migrations on startup, which is what actually creates the notification
// trigger/trigger function generated by PgNotify.Migrations (pulled in transitively through
// PgNotify.Writer) — see Migrations/ for the checked-in migration produced by
// `dotnet ef migrations add InitialCreate`. This app never listens for its own notifications; see
// ../Orders.Projector for the separate process that does.
using (var scope = app.Services.CreateScope())
{
    await scope.ServiceProvider.GetRequiredService<SampleDbContext>().Database.MigrateAsync();
}

app.MapOrderEndpoints();

app.Run();

public partial class Program;
