// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskBoard.WebApi;

#nullable disable

namespace TaskBoard.WebApi.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    partial class SampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskBoard.Model.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TaskItem");

                    b
                        .HasAnnotation("Notifications:ChannelNameOverride", null)
                        .HasAnnotation("Notifications:ChannelStrategyArgument", null)
                        .HasAnnotation("Notifications:ChannelStrategyKind", "PerEntity")
                        .HasAnnotation("Notifications:Enabled", true)
                        .HasAnnotation("Notifications:NamePrefix", null)
                        .HasAnnotation("Notifications:Operations", "Insert,Update,Delete")
                        .HasAnnotation("Notifications:PayloadBuilderKind", "Minimal")
                        .HasAnnotation("Notifications:PayloadBuilderTypeName", null)
                        .HasAnnotation("Notifications:PayloadColumns", "")
                        .HasAnnotation("Notifications:PayloadOverflow", "Truncate")
                        .HasAnnotation("Notifications:WatchedUpdateColumns", "");
                });
#pragma warning restore 612, 618
        }
    }
}
